Cart
ishant005/Ecommerce pull request #3
Opened 2022-03-14 11:12 UTC by ishant005

2022-03-14 13:17 UTC, kushalsourav approved these changes
everything looks good to me , good work

2022-03-16 07:03 UTC, anupkgurung requested changes
Please go through the comments

2022-03-16 07:03 UTC, anupkgurung commented on Home.css
> +li {
Do not add style directly to element.

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.css
> +:root {
keep all the variables in one file and use that.

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.css
> +* {
styles for all(*) should also be in there in one and not individually for every file

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.css
> +    height: 14.3rem;
why height 14.3 ? was it calculated ?

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.css
> +    display: flex;
display flex and flex direction are used widely move it into a common or utility class.

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.css
> +    border-radius: 4px;
how is height calculated 14.3?

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.html
> +    <title>My cart</title>
Use meta tags for description also.

2022-03-16 07:03 UTC, anupkgurung commented on mycart/cart.html
> +                            add_circle_outline
Use proper indentation or do format the code before commit for good readability.

2022-03-16 07:03 UTC, anupkgurung commented on Home.html
> +        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
use meta for description also

2022-03-16 07:03 UTC, anupkgurung commented on Home.css
> +
remove unused space.

2022-03-16 07:03 UTC, anupkgurung commented on Home.css
> +    line-height: 1.5;
why padding auto and padding-right are used simultaneously ?

2022-03-16 08:27 UTC, ishant005 commented on Home.css
> +li {
Ok .will refactor it

2022-03-16 08:27 UTC, ishant005 commented on mycart/cart.css
> +:root {
ok

2022-03-16 08:27 UTC, ishant005 commented on mycart/cart.css
> +    height: 14.3rem;
resolved

2022-03-16 08:28 UTC, merged