wishlist page added
ishant005/Ecommerce pull request #5
Opened 2022-03-14 11:14 UTC by ishant005

2022-03-14 13:30 UTC, kushalsourav approved these changes
nice work , naming conventions is good

2022-03-16 07:08 UTC, anupkgurung requested changes
Please go through the comments

2022-03-16 07:08 UTC, anupkgurung commented on wishlist/wishlist.css
> +    text-align: center;
use text align as utility class as it is used multiple times.

2022-03-16 07:08 UTC, anupkgurung commented on wishlist/wishlist.html
> +        <link rel="stylesheet" href="/productpage/product.css" />
why are you using product & wishlist css if it's already included in style css ?

2022-03-16 08:29 UTC, merged